### PR TITLE
Add Service account annotations configuration

### PR DESCRIPTION
**Pull request by PierreBesson**
#### What this PR does / why we need it

This PR allows setting annotations to the service account. Those annotations are useful in the context of a Cloud Provider, eg. to set workload-identities. 

#### Checklist

- [x] Chart Version bumped
- [x] [CLA signed](https://cla-assistant.io/timescale/helm-charts)

### CODE REVIEW

**Comment by paulfantom** [comment]
Sorry, but multinode helm chart is not maintained and as such we cannot merge your PR until we find community maintainers. Would you wish to become one?

**Review by paulfantom — CHANGES_REQUESTED** [review]
Could you include changes only for the timescaledb-single helm chart?

**Comment by PierreBesson** [comment]
> Could you include changes only for the timescaledb-single helm chart?

I removed it from my PR

**Comment by paulfantom** [comment]
Could you also bump the timescaledb-single chart minor version?

**Review by paulfantom — APPROVED** [review]

**Pull request merged**
