### PR TITLE
allow curl image override

### PR DESCRIPTION
**Pull request by pitwegner**

### CODE REVIEW

**Comment by nhudson** [comment]
@pchang388 looks like the author of this PR might not be responding.  @pitwegner if you can sign the CLA bot and rebase from main I can get this PR merged, until then it's most likely in limbo unless someone else comes along to supersede this PR.

**Comment by pchang388** [comment]
Hi @nhudson  - let me try and make a PR then with updated comments in addition to his changes

**Comment by pchang388** [comment]
@nhudson  - first time trying to contribute to this repo and tried my best to follow the contributers guide, Opened new PR with updated comments and also other changes: https://github.com/timescale/helm-charts/pull/556

Thanks!

**Comment by pchang388** [comment]
@nhudson  - I had some issues with my email and CLA agreement being signed but finally fixed it, new PR with CLA signed here: https://github.com/timescale/helm-charts/pull/558

**Pull request closed without merging**
