### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alejandrodnm**
Signed-off-by: alejandrodnm <alejandrodnm@gmail.com>

#### Which issue this PR fixes

- fixes README

#### Checklist

- [x] Chart Version bumped
- [x] [CLA signed](https://cla-assistant.io/timescale/helm-charts)

### CODE REVIEW

**Review by onprem — APPROVED** [review]
Thanks! Got caught by you again haha.

**Comment by onprem** [comment]
You'd need to bump the chart version though, for how our CI works.

**Comment by alejandrodnm** [comment]
@onprem do I need to bump the chart version just for this change?

**Comment by onprem** [comment]
@alejandrodnm Yes, we have CD setup to release a new version of chart with every PR. Since the README file is under the chart directory, we need to bump the version. Here we can just do a patch release.

**Comment by alejandrodnm** [comment]
@onprem the errors are related to a fix for the alerts that was made in this PR https://github.com/timescale/promscale/pull/1794 Is there something else I need to do?

**Comment by alejandrodnm** [comment]
I'll leave this open until the alerts are fixed on another PR

**Comment by onprem** [comment]
I have created #541 for the alerts. And these checks are unrelated and not required for this PR so I am going ahead and merging. Thanks!

**Pull request merged**
